[project]
name = "ppalgannal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "rektpunk@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.ruff.lint]
select = ["B","E","F","I","UP","SIM"]
ignore = ["E501"]
